config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :asignaturas
  resources :grados
  resources :universidads
  resources :comunidads
  root 'static_pages#index'
  get 'static_pages/index'

  get '/universidads/scrape/:idUniversidad', to: "universidads#scrape" , as: "universidads_scrape"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/asignatura.rb
class Asignatura < ApplicationRecord
  belongs_to :grado

  ThinkingSphinx::Callbacks.append(
    self, :behaviours => [:sql]
  )

  def self.createAsignatura(item2)

    nombre = item2[:nombre]
    grado_g = item2[:grado]
    grado=grado_g.nombre
    universidad= grado_g.universidad.nombre
    asignaturas = Asignatura.where("nombre = ?", nombre).and(Asignatura.where("grado.nombre = ?",  grado)).and(Asignatura.where("grado.universidad.nombre = ?",  universidad))
    if asignaturas.count<1

    Asignatura.where(item2).create
                  
    end
  end
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  before_action :set_asignatura, only: %i[ show edit update destroy ]

  # GET /asignaturas or /asignaturas.json
  def index
    @asignaturas = Asignatura.all
  end

  # GET /asignaturas/1 or /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
  end

  # POST /asignaturas or /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: "Asignatura was successfully created." }
        format.json { render :show, status: :created, location: @asignatura }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asignaturas/1 or /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: "Asignatura was successfully updated." }
        format.json { render :show, status: :ok, location: @asignatura }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1 or /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: "Asignatura was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre, :tipo, :creditos, :grado_id)
    end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_form.html.erb
<%= form_with(model: asignatura) do |form| %>
  <% if asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>

      <ul>
        <% asignatura.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="field">
    <%= form.label :creditos %>
    <%= form.number_field :creditos %>
  </div>

  <div class="field">
    <%= form.label :grado_id %>
    <%= form.text_field :grado_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/asignaturas/edit.html.erb
<h1>Editing Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Show', @asignatura %> |
<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asignaturas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Tipo</th>
      <th>Creditos</th>
      <th>Grado</th>
      <th>Universidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @asignaturas.each do |asignatura| %>
      <tr>
        <td><%= asignatura.nombre %></td>
        <td><%= asignatura.tipo %></td>
        <td><%= asignatura.creditos %></td>
        <td><%= asignatura.grado.nombre %></td>
        <td><%= asignatura.grado.universidad.nombre %></td>
        <td><%= link_to 'Show', asignatura %></td>
        <td><%= link_to 'Edit', edit_asignatura_path(asignatura) %></td>
        <td><%= link_to 'Destroy', asignatura, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asignatura', new_asignatura_path %>

app/views/asignaturas/new.html.erb
<h1>New Asignatura</h1>

<%= render 'form', asignatura: @asignatura %>

<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @asignatura.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @asignatura.tipo %>
</p>

<p>
  <strong>Creditos:</strong>
  <%= @asignatura.creditos %>
</p>

<p>
  <strong>Grado:</strong>
  <%= @asignatura.grado_id %>
</p>

<%= link_to 'Edit', edit_asignatura_path(@asignatura) %> |
<%= link_to 'Back', asignaturas_path %>