config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :asignaturas
  resources :grados
  resources :universidads
  resources :comunidads
  root 'static_pages#index'
  get 'static_pages/index'

  get '/universidads/scrape/:idUniversidad', to: "universidads#scrape" , as: "universidads_scrape"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/grado.rb
class Grado < ApplicationRecord
  belongs_to :universidad
  has_many :asignaturas

  def self.compruebaGrado(item2)

  end

    
end

app/controllers/grados_controller.rb
class GradosController < ApplicationController
  before_action :set_grado, only: %i[ show edit update destroy ]

  # GET /grados or /grados.json
  def index
    @grados = Grado.all
  end

  # GET /grados/1 or /grados/1.json
  def show
  end

  # GET /grados/new
  def new
    @grado = Grado.new
  end

  # GET /grados/1/edit
  def edit
  end

  # POST /grados or /grados.json
  def create
    @grado = Grado.new(grado_params)

    respond_to do |format|
      if @grado.save
        format.html { redirect_to @grado, notice: "Grado was successfully created." }
        format.json { render :show, status: :created, location: @grado }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grados/1 or /grados/1.json
  def update
    respond_to do |format|
      if @grado.update(grado_params)
        format.html { redirect_to @grado, notice: "Grado was successfully updated." }
        format.json { render :show, status: :ok, location: @grado }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grados/1 or /grados/1.json
  def destroy
    @grado.destroy
    respond_to do |format|
      format.html { redirect_to grados_url, notice: "Grado was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grado
      @grado = Grado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grado_params
      params.require(:grado).permit(:nombre, :url, :universidad_id)
    end
end

app/helpers/grados_helper.rb
module GradosHelper
end

app/views/grados/_form.html.erb
<%= form_with(model: grado) do |form| %>
  <% if grado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grado.errors.count, "error") %> prohibited this grado from being saved:</h2>

      <ul>
        <% grado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :universidad_id %>
    <%= form.text_field :universidad_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grados/edit.html.erb
<h1>Editing Grado</h1>

<%= render 'form', grado: @grado %>

<%= link_to 'Show', @grado %> |
<%= link_to 'Back', grados_path %>

app/views/grados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grados</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Url</th>
      <th>Universidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grados.each do |grado| %>
      <tr>
        <td><%= grado.nombre %></td>
        <td><%= grado.url %></td>
        <td><%= grado.universidad.nombre %></td>
        <td><%= link_to 'Show', grado %></td>
        <td><%= link_to 'Edit', edit_grado_path(grado) %></td>
        <td><%= link_to 'Destroy', grado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grado', new_grado_path %>

app/views/grados/new.html.erb
<h1>New Grado</h1>

<%= render 'form', grado: @grado %>

<%= link_to 'Back', grados_path %>

app/views/grados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @grado.nombre %>
</p>

<p>
  <strong>Url:</strong>
  <%= @grado.url %>
</p>

<p>
  <strong>Universidad:</strong>
  <%= @grado.universidad_id %>
</p>

<%= link_to 'Edit', edit_grado_path(@grado) %> |
<%= link_to 'Back', grados_path %>