config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :asignaturas
  resources :grados
  resources :universidads
  resources :comunidads
  root 'static_pages#index'
  get 'static_pages/index'

  get '/universidads/scrape/:idUniversidad', to: "universidads#scrape" , as: "universidads_scrape"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/universidad.rb
class Universidad < ApplicationRecord
  validates :nombre, uniqueness: true
  validates :name, :url, :email, presence: true
  belongs_to :comunidad
  has_many :grados
  
end

app/controllers/universidads_controller.rb
class UniversidadsController < ApplicationController
  before_action :set_universidad, only: %i[ show edit update destroy ]

  # GET /universidads or /universidads.json
  def index
    @universidads = Universidad.all
    
  end

  # GET /universidads/1 or /universidads/1.json
  def show
    
  end

  def scrape
    universidad= Universidad.find(params[:idUniversidad])
    nombre_universidad= universidad.nombre
    url = universidad.url 
    case nombre_universidad
    when "Universidad Carlos III de Madrid"
      response = Uc3mSpider.process(url,universidad)
  
    when "Universidad Alfonso X el Sabio"
      response = UaxSpider.process(url,universidad)
    when "Universidad de Alcalá"
      response = UahSpider.process(url,universidad)

    when "Universidad Nebrija"
      response = UnebrijaSpider.process(url,universidad)
    when "Universidad Camilo José Cela"
      response = UcamilojcSpider.process(url,universidad)
    when "Universidad CEU San Pablo"
      response = UceuSpider.process(url,universidad)
    when "Universidad Europea de Madrid"
      response = UemSpider.process(url,universidad)
    when "Universidad Juan Carlos I"
      response = UrjcSpider.process(url,universidad)

    end


  end
  

  # GET /universidads/new
  def new
    @universidad = Universidad.new
  end

  # GET /universidads/1/edit
  def edit
  end

  # POST /universidads or /universidads.json
  def create
    @universidad = Universidad.new(universidad_params)

    respond_to do |format|
      if @universidad.save
        format.html { redirect_to @universidad, notice: "Universidad was successfully created." }
        format.json { render :show, status: :created, location: @universidad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @universidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universidads/1 or /universidads/1.json
  def update
    respond_to do |format|
      if @universidad.update(universidad_params)
        format.html { redirect_to @universidad, notice: "Universidad was successfully updated." }
        format.json { render :show, status: :ok, location: @universidad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @universidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universidads/1 or /universidads/1.json
  def destroy
    @universidad.destroy
    respond_to do |format|
      format.html { redirect_to universidads_url, notice: "Universidad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_universidad
      @universidad = Universidad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def universidad_params
      params.require(:universidad).permit(:nombre, :tipo, :url, :comunidad_id)
    end
end

app/helpers/universidads_helper.rb
module UniversidadsHelper
end

app/views/universidads/_form.html.erb
<%= form_with(model: universidad) do |form| %>
  <% if universidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(universidad.errors.count, "error") %> prohibited this universidad from being saved:</h2>

      <ul>
        <% universidad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.select :tipo, [ 'Pública', 'Privada' ], :prompt => 'Seleccione una' %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :comunidad_id %>
    <%= form.select :comunidad_id, options_from_collection_for_select(Comunidad.all, :id, :nombre) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/universidads/_universidades.html.erb
<div class="card">
  <div class="card-header">
    <div class="fa fa-book"></div>
    <%= universidad.nombre %>
  </div>
  <div class="card-body">
  <div class="far fa-chalkboard-teacher"></div>
    <a href="<%= universidad.url %>"><%= universidad.url %></a>
    
  </div>
  <div class="card-footer">
    
    <div class="row"></div>
    <div class="fas fa-dollar-sign"></div>
    <%= universidad.tipo%>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', universidad, class: 'btn btn-outline-primary' %>
    <%= link_to 'Edit', edit_universidad_path(universidad), class: 'btn btn-outline-warning' %>
    <%= link_to 'Destroy', universidad, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
    <td><%= link_to 'Scrape', universidads_scrape_path(universidad.id), class: 'btn btn-outline-success'  %></td>
  </div>
</div>

app/views/universidads/edit.html.erb
<h1>Editing Universidad</h1>

<%= render 'form', universidad: @universidad %>

<%= link_to 'Show', @universidad %> |
<%= link_to 'Back', universidads_path %>

app/views/universidads/index.html.erb
<div class="card-columns">
  <% @universidads.each do |universidad| %>
    <%= render 'universidads/universidades', universidad: universidad %>
  <% end %>
</div>

app/views/universidads/new.html.erb
<h1>New Universidad</h1>

<%= render 'form', universidad: @universidad %>

<%= link_to 'Back', universidads_path %>

app/views/universidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @universidad.nombre %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @universidad.tipo %>
</p>

<p>
  <strong>Url:</strong>
  <%= @universidad.url %>
</p>

<p>
  <strong>Comunidad:</strong>
  <%= @universidad.comunidad_id %>
</p>

<%= link_to 'Edit', edit_universidad_path(@universidad) %> |
<%= link_to 'Back', universidads_path %>