config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :asignaturas
  resources :grados
  resources :universidads
  resources :comunidads
  root 'static_pages#index'
  get 'static_pages/index'

  get '/universidads/scrape/:idUniversidad', to: "universidads#scrape" , as: "universidads_scrape"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comunidad.rb
class Comunidad < ApplicationRecord
    has_many :universidads
    validates :nombre, uniqueness: true
end

app/controllers/comunidads_controller.rb
class ComunidadsController < ApplicationController
  before_action :set_comunidad, only: %i[ show edit update destroy ]

  # GET /comunidads or /comunidads.json
  def index
    @comunidads = Comunidad.all
  end

  # GET /comunidads/1 or /comunidads/1.json
  def show
  end

  # GET /comunidads/new
  def new
    @comunidad = Comunidad.new
  end

  # GET /comunidads/1/edit
  def edit
  end

  # POST /comunidads or /comunidads.json
  def create
    @comunidad = Comunidad.new(comunidad_params)

    respond_to do |format|
      if @comunidad.save
        format.html { redirect_to @comunidad, notice: "Comunidad was successfully created." }
        format.json { render :show, status: :created, location: @comunidad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comunidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comunidads/1 or /comunidads/1.json
  def update
    respond_to do |format|
      if @comunidad.update(comunidad_params)
        format.html { redirect_to @comunidad, notice: "Comunidad was successfully updated." }
        format.json { render :show, status: :ok, location: @comunidad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comunidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comunidads/1 or /comunidads/1.json
  def destroy
    @comunidad.destroy
    respond_to do |format|
      format.html { redirect_to comunidads_url, notice: "Comunidad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comunidad
      @comunidad = Comunidad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comunidad_params
      params.require(:comunidad).permit(:nombre)
    end
end

app/helpers/comunidads_helper.rb
module ComunidadsHelper
end

app/views/comunidads/_form.html.erb
<%= form_with(model: comunidad) do |form| %>
  <% if comunidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comunidad.errors.count, "error") %> prohibited this comunidad from being saved:</h2>

      <ul>
        <% comunidad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comunidads/edit.html.erb
<h1>Editing Comunidad</h1>

<%= render 'form', comunidad: @comunidad %>

<%= link_to 'Show', @comunidad %> |
<%= link_to 'Back', comunidads_path %>

app/views/comunidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comunidads</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comunidads.each do |comunidad| %>
      <tr>
        <td><%= comunidad.nombre %></td>
        <td><%= link_to 'Show', comunidad %></td>
        <td><%= link_to 'Edit', edit_comunidad_path(comunidad) %></td>
        <td><%= link_to 'Destroy', comunidad, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comunidad', new_comunidad_path %>

app/views/comunidads/new.html.erb
<h1>New Comunidad</h1>

<%= render 'form', comunidad: @comunidad %>

<%= link_to 'Back', comunidads_path %>

app/views/comunidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @comunidad.nombre %>
</p>

<%= link_to 'Edit', edit_comunidad_path(@comunidad) %> |
<%= link_to 'Back', comunidads_path %>